sudo: false
language: go
git:
  depth: 1
install:
- wget https://github.com/gohugoio/hugo/releases/download/v0.72.0/hugo_0.72.0_Linux-64bit.tar.gz
- tar -xzvf hugo_0.72.0_Linux-64bit.tar.gz
- chmod +x hugo
- export PATH=$PATH:$PWD
- hugo version
script: hugo
deploy:
  provider: pages
  skip_cleanup: true
  github_token: 2c0e72c1c0776a4f27413fd51b71d3cd3750312f
  on:
    branch: master
  local_dir: public
  repo: DexSinis/DexSinis.github.io
  fqdn: <custom-domain-if-needed>
  target_branch: master
  email: 343731621@qq.com
  name: DexSinis
