sudo: false
language: go
git:
  depth: 1
install: go get -v github.com/gohugoio/hugo
script: hugo
deploy:
  provider: pages
  skip_cleanup: true
  github_token: 2c0e72c1c0776a4f27413fd51b71d3cd3750312f
  on:
    branch: master
  local_dir: public
  repo: DexSinis/DexSinis.github.io
  fqdn: <custom-domain-if-needed>
  target_branch: master
  email: 343731621@qq.com
  name: DexSinis
