sudo: false
language: go
git:
  depth: 1
install:
  - wget https://github.com/gohugoio/hugo/releases/download/v0.72.0/hugo_0.72.0_Linux-64bit.tar.gz
  - tar -xzvf hugo_0.72.0_Linux-64bit.tar.gz
  - chmod +x hugo
  - export PATH=$PATH:$PWD
  - hugo version
script: hugo --theme book
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  on:
    branch: master
  local_dir: public
  repo: DexSinis/coding-pages-bucket-1252010-8426029-13858-520654-1253682189.cos-website.ap-hongkong.myqcloud.com
  fqdn: <custom-domain-if-needed>
  target_branch: master
  email: 343731621@qq.com
  name: DexSinis
